#!/bin/busybox sh

INIT_SCRIPT="/usr/app/start_script/start.sh"

run_script() {
    local script="$1"
    /bin/busybox sh "$script" &
}

start() {
    local script_dir="${1:-/usr/app/start_script}"

    if [ ! -d "$script_dir" ]; then
        exit 1
    fi

    scripts=$(/bin/busybox find "$script_dir" -maxdepth 1 -type f \( -name "*.sh" -o -executable \))

    if [ -z "$scripts" ]; then
        exit 0
    fi

    for script in $scripts; do
        run_script "$script"
    done
}

# See how we were called.
case "$1" in
	start)
		# start
        run_script "$INIT_SCRIPT"
		;;
	stop)
		# stop
		;;
	restart)
		# stop
		# start
		;;
	reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit 0